version: '3'
services:
  terria-map:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    restart: unless-stopped
    volumes:
      - ".:/app"
      - "/app/node_modules"
